### ISSUE TITLE
Bazel error

### ISSUE THREAD

**Issue by blacksector** [llSourcell/AI_Reader#3]
Hey man, first of all to start, LOVE the videos!

I have found a problem with utils/utf8/... when I run the bazel command I am thrown with this:
```bash
ERROR: no targets found beneath 'utils/utf8'.
INFO: Elapsed time: 0.102s
ERROR: Couldn't start the build. Unable to run tests.
```
could this be an issue as to why I cannot run the python script `test.p`? To point out my error looks like the following:
```python
syntaxnet/demo.sh: line 31: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 43: bazel-bin/syntaxnet/parser_eval: No such file or directory
syntaxnet/demo.sh: line 55: bazel-bin/syntaxnet/conll2tree: No such file or directory
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    root = demo_lib.get_root_word(dep_tree)
  File "/root/Desktop/AI_Reader-master/syntaxnet/demo_lib.py", line 21, in get_root_word
    root = dependency_tree[2].split()[0]
IndexError: list index out of range
```

Thanks in advance!

**Comment by blacksector** [comment]
Update on the issue. I just realized it is `util/utf8` by accident I added a `s` but now I have another issue:
```bash
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path.
```
Problem is I do not have a graphics card like nVidia on my laptop and while building Tensorflow I did not add Cuda support, what should I do? Would I need to use something like AWS to compile this or can the code be modified to work without GPU?

**Comment by baditaflorin** [comment]
I have the same prolem, what could i do ?

I`m using a virtual machine

**Comment by blacksector** [comment]
@baditaflorin Unfortunately have not found a solution yet.
